# This config file builds an image using the local component. Usefult for debugging.

external_components:
  - source:
      type: local
      path: esphome/components

logger:
  level: DEBUG

esphome:
  name: dc-blue-test
  platform: ESP32
  board: esp32dev
  build_path: .build/dc_blue_test

dc_blue:
  data_pin: GPIO33
  trigger_pin: GPIO32
#  symbol_period: 900

binary_sensor:
  - platform: dc_blue
    light:
      name: "Garage Motor Light"

cover:
  - platform: dc_blue
    name: "Garage Door"
    device_class: garage
